services:
  yapo-postgres:
    image: postgres:18.3-alpine
    container_name: "YAPO-postgres"
    restart: always
    ports:
      - "${POSTGRES_EXPOSED_HOST:-127.0.0.1}:${POSTGRES_EXPOSED_PORT:-54323}:${POSTGRES_PORT:-5432}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-django6}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-django6}
      - POSTGRES_DB=${POSTGRES_DB:-django6}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U $${POSTGRES_USER:-django6} -d $${POSTGRES_DB:-django6}'",
        ]
      interval: 5s
      timeout: 1s
      retries: 11
    volumes:
      - yapo-postgres-data:/var/lib/postgresql/data

  yapo-redis:
    image: "redis:alpine"
    container_name: YAPO-redis
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 1s
      retries: 10

  yapo-django:
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfiles/django.dockerfile
    volumes:
      - ./src:/usr/src/app:rw
    ports:
      - "8000:8000"
    depends_on:
      yapo-redis:
        condition: service_healthy
      yapo-postgres:
        condition: service_healthy
    env_file:
      - ./env/django.env
      - ./env/db.env
      - ./env/cache.env
      - ./env/celery.env
    command: "/bin/sh -c 'python3 manage.py runserver 0.0.0.0:8000'"
    container_name: YAPO-django

  yapo-celery-worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfiles/django.dockerfile
    command: celery -A YAPO worker -l info
    volumes:
      - ./src:/usr/src/app:rw
    depends_on:
      - yapo-django
    env_file:
      - ./env/django.env
      - ./env/db.env
      - ./env/cache.env
      - ./env/celery.env
    container_name: YAPO-celery-worker

  yapo-celery-beat:
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfiles/django.dockerfile
    command: celery -A YAPO beat -l info
    volumes:
      - ./src:/usr/src/app:rw
    depends_on:
      - yapo-django
    env_file:
      - ./env/django.env
      - ./env/db.env
      - ./env/cache.env
      - ./env/celery.env
    container_name: YAPO-celery-beat

volumes:
  yapo-postgres-data:
