export enum PlantSoil {
  POTTING_SOIL = "POTTING_SOIL",
  UNIVERSAL_SOIL = "UNIVERSAL_SOIL",
  PEAT_SOIL = "PEAT_SOIL",
  SANDY_SOIL = "SANDY_SOIL",
  LOAMY_SOIL = "LOAMY_SOIL",
  CLAY_SOIL = "CLAY_SOIL",
  COMPOST_SOIL = "COMPOST_SOIL",
  CACTUS_SOIL = "CACTUS_SOIL",
  HERB_SOIL = "HERB_SOIL",
  VEGETABLE_SOIL = "VEGETABLE_SOIL",
  ACIDIC_SOIL = "ACIDIC_SOIL",
  ALKALINE_SOIL = "ALKALINE_SOIL",
  NEUTRAL_SOIL = "NEUTRAL_SOIL",
  PERLITE_MIX = "PERLITE_MIX",
  COCONUT_SUBSTRATE = "COCONUT_SUBSTRATE",
  ORCHID_SOIL = "ORCHID_SOIL"
}
