export enum PlantCondition {
  HEALTHY = "HEALTHY",
  NEEDS_WATER = "NEEDS_WATER",
  NEEDS_SUNLIGHT = "NEEDS_SUNLIGHT",
  NEEDS_FERTILIZER = "NEEDS_FERTILIZER",
  DIEBACK = "DIEBACK",
  INFESTED = "INFESTED",
  DISEASED = "DISEASED",
  STRESSED = "STRESSED",
  FUCK_THIS_SHIT_IM_OUT = "FUCK_THIS_SHIT_IM_OUT"
}
